services:
  configurator:
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
    depends_on:
      - redis-cache
      - redis-queue

  redis-cache:
    image: ccr.ccs.tencentyun.com/iniself/redis:6.2-alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: ccr.ccs.tencentyun.com/iniself/redis:6.2-alpine
    volumes:
      - redis-queue-data:/data

volumes:
  redis-cache-data:
  redis-queue-data:
